{% set name = "libta-lib" %}
{% set version = "0.6.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/TA-Lib/ta-lib/archive/refs/tags/v{{ version }}.tar.gz
    sha256: a2fac51f4f1d4804dd2edd1701d52bb9728a5c2ec936d0c5d9a222c49f57d77b
    folder: src

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ stdlib('cxx') }}
    - make
    - cmake

test:
  commands:
    - test -f $PREFIX/lib/libta_lib${SHLIB_EXT}     # [unix]
    - test -f $PREFIX/include/ta-lib/ta_abstract.h  # [unix]
    - test -f $PREFIX/include/ta-lib/ta_common.h    # [unix]
    - test -f $PREFIX/include/ta-lib/ta_defs.h      # [unix]
    - test -f $PREFIX/include/ta-lib/ta_func.h      # [unix]
    - if exist %LIBRARY_INC%\ta_abstract.h (exit 0) else (exit 1)         # [win]
    - if exist %LIBRARY_INC%\ta_common.h (exit 0) else (exit 1)           # [win]
    - if exist %LIBRARY_INC%\ta_defs.h (exit 0) else (exit 1)             # [win]
    - if exist %LIBRARY_INC%\ta_func.h (exit 0) else (exit 1)             # [win]
    - if exist %LIBRARY_LIB%\ta_abstract_cdd.lib (exit 0) else (exit 1)   # [win]
    - if exist %LIBRARY_LIB%\ta_common_cdr.lib (exit 0) else (exit 1)     # [win]
    - if exist %LIBRARY_LIB%\ta_func_cmd.lib (exit 0) else (exit 1)       # [win]
    - if exist %LIBRARY_LIB%\ta_libc_csd.lib (exit 0) else (exit 1)       # [win]
    - if exist %LIBRARY_LIB%\ta_libc_csr.lib (exit 0) else (exit 1)       # [win]

about:
  home: https://ta-lib.org/index.html
  summary: "TA-Lib : Technical Analysis Library"
  license: BSD-2-Clause
  # License is included in the repo, not in the src package:
  license_file: src/LICENSE.TXT

extra:
  recipe-maintainers:
    - gerrymanoim
    - llllllllll
    - richafrank
    - sanurielf
