{% set name = "libta-lib" %}
{% set version = "0.6.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ta-lib/ta-lib/releases/download/v0.6.4/ta-lib-0.6.4-src.tar.gz  # [unix]
    sha256: aa04066d17d69c73b1baaef0883414d3d56ab3775872d82916d1cdb376a3ae86                    # [unix]
    folder: unix                                                                                # [unix]
  - url: https://github.com/TA-Lib/ta-lib/archive/refs/tags/v0.6.4.zip
    sha256: 33e99e0f4c2102b544619e038a00169d5b2f0577c5328e5736f3c5c443ed49bd
    folder: win

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make       # [unix]

test:
  commands:
    - test -f $PREFIX/lib/libta_lib${SHLIB_EXT}     # [unix]
    - test -f $PREFIX/include/ta-lib/ta_abstract.h  # [unix]
    - test -f $PREFIX/include/ta-lib/ta_common.h    # [unix]
    - test -f $PREFIX/include/ta-lib/ta_defs.h      # [unix]
    - test -f $PREFIX/include/ta-lib/ta_func.h      # [unix]
    - if exist %LIBRARY_INC%\ta_abstract.h (exit 0) else (exit 1)         # [win]
    - if exist %LIBRARY_INC%\ta_common.h (exit 0) else (exit 1)           # [win]
    - if exist %LIBRARY_INC%\ta_defs.h (exit 0) else (exit 1)             # [win]
    - if exist %LIBRARY_INC%\ta_func.h (exit 0) else (exit 1)             # [win]
    - if exist %LIBRARY_LIB%\ta_abstract_cdd.lib (exit 0) else (exit 1)   # [win]
    - if exist %LIBRARY_LIB%\ta_common_cdr.lib (exit 0) else (exit 1)     # [win]
    - if exist %LIBRARY_LIB%\ta_func_cmd.lib (exit 0) else (exit 1)       # [win]
    - if exist %LIBRARY_LIB%\ta_libc_csd.lib (exit 0) else (exit 1)       # [win]
    - if exist %LIBRARY_LIB%\ta_libc_csr.lib (exit 0) else (exit 1)       # [win]

about:
  home: https://ta-lib.org/index.html
  summary: "TA-Lib : Technical Analysis Library"
  license: BSD-2-Clause
  # License is included in windows source download, but not unix:
  license_file: win/LICENSE.TXT

extra:
  recipe-maintainers:
    - gerrymanoim
    - llllllllll
    - richafrank
